### ISSUE TITLE
Update after div is rendered

### ISSUE THREAD

**Issue by jcarlosfern** [nkovacic/angular-touchspin#24] opened 2019-01-12 21:17 UTC
How can I send a value after the div has been draw? If I put a value to the var in the controller it is working fine, but when I load it from a web service, it always return 0 because it don't update the number. 

Thanks for the help

**Comment by nkovacic** [comment] 2019-01-13 10:03
Maybe a [plunkr](https://plnkr.co/) or [stackblitz](https://stackblitz.com/) example of your issue? Unfortunately I do not understand what the problem is without a clear example.

You can find an example [here](https://stackblitz.com/edit/angular-touchspin-example)

**Comment by nkovacic** [comment] 2019-01-28 05:44
Closing this for now. If an example is shown I will reopen it.

**Closed as completed by nkovacic** 2019-01-28 05:44 UTC
